title: "MacAdmins Conference 2025"
description: "Conference for Apple IT professionals"
baseurl: "/website" # important!
url: "https://psu-macadmins-conf.github.io"

# remote_theme: "mmistakes/minimal-mistakes"
remote_theme: "Phlow/feeling-responsive"
plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single

locale: "en-US"
logo: "/assets/images/logo.png"
minimal_mistakes_skin: "default"

navigation:
  data: navigation

header:
  navigation: true

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: https://x.com/macadminsconf
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: https://www.facebook.com/macadminsconf
    # - label: "Bluesky"
    #   icon: "fab fa-fw fa-bluesky
    #   url: https://bsky.app/profile/macadminsconf.bsky.social
    # - label: "Mastodon"
    #   icon: "fab fa-fw fa-mastodon"
    #   url: https://mastodon.social/@macadminsconf
