title: "MacAdmins Conference 2025"
description: "Conference for Apple IT professionals"
baseurl: "/website" # important!
url: "https://psu-macadmins-conf.github.io"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single

locale: "en-US"
logo: "/website/assets/images/banner.jpg"
minimal_mistakes_skin: "default"

