title: "MacAdmins Conference 2025"
description: "Conference for Apple IT professionals"
baseurl: "/website" # important!
url: "https://psu-macadmins-conf.github.io"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single

locale: "en-US"
logo: "/assets/images/logo.png"
minimal_mistakes_skin: "default"

navigation:
  data: navigation

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-brands fa-square-twitter"
      url: https://x.com/macadminsconf
    - label: "Facebook"
      icon: "fab fa-brands fa-square-facebook"
      url: https://www.facebook.com/macadminsconf
    - label: "Bluesky"
      icon: "fab fa-brands fa-bluesky
      url: https://bsky.app/profile/macadminsconf.bsky.social
    - label: "Mastodon"
      icon: "fab fa-brands fa-mastodon"
      url: https://mastodon.social/@macadminsconf
