title: MacAdmins Conference 2025
description: Premier East Coast conference for Apple IT professionals.
url: "https://macadmins.psu.edu" # your future custom domain
baseurl: "" # empty for custom domain or root

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single

author:
  name: MacAdmins Team
  avatar: /assets/images/logo.png

